title: 'Heliophysics System Observatory'
author: Amr Alshatnawi and Barbara J Thompson 

logo: ../css/logo.png

html: 
  favicon: logo.png
  home_page_in_navbar : false
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true

repository:
  url: "https://github.com/AmrAlshatnawi/HSOConnect"
  branch: master
  path_to_book: book

latex:
  latex_engine              : xelatex

execute:
  execute_notebooks         : off

launch_buttons:
  binder             : false
  binderhub          : false
  binderhub_url      : off
  jupyterhub         : false
  thebe              : false
  colab              : false

sphinx:
  config:
    html_show_copyright: false
    myst_amsmath_enable: true
